create table AMF_Account (
	accountId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	createDate DATE null,
	modifiedDate DATE null,
	firstName VARCHAR(75) null,
	lastName VARCHAR(75) null,
	emailAddress VARCHAR(75) null,
	userName VARCHAR(75) null,
	genre VARCHAR(75) null,
	birthday VARCHAR(75) null,
	password_ VARCHAR(75) null,
	confirmPassword VARCHAR(75) null,
	homePhone VARCHAR(75) null,
	mobilePhone VARCHAR(75) null,
	address1 VARCHAR(75) null,
	address2 VARCHAR(75) null,
	city VARCHAR(75) null,
	state_ VARCHAR(75) null,
	zipCode VARCHAR(75) null,
	securityQuestion VARCHAR(75) null,
	answer VARCHAR(75) null,
	termsOfUse BOOLEAN
);